### ISSUE TITLE
使用Json格式发送的时候一直没有收到数据

### ISSUE THREAD

**Issue by kolyneh** [baidao/bizsocket#5]
使用Json格式发送的时候一直没有收到数据， 不知道是不是我的使用问题。
作者可否给些例子来参考

**Comment by typ0520** [comment]
你看下这个
https://github.com/typ0520/bizsocket/tree/master/sample-rx2/j2se

**Comment by kolyneh** [comment]
嗯嗯，我是参照这里写的，
改写了SamplePacket. 如下：


  override fun toBytes(): ByteArray {
        //TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
        val bos = ByteArrayOutputStream()
        val bufferedSink = Okio.buffer(Okio.sink(bos))

        try {
            //包长 = 内容长度 + 包头固定的12个字节
            val byteString = ByteString.encodeUtf8(contentStr)
            /* bufferedSink.writeInt(byteString.size() + 12)
             bufferedSink.writeInt(cmd)
             bufferedSink.writeInt(seq)*/
            bufferedSink.write(byteString)
            bufferedSink.flush()
        } catch (e: IOException) {
            e.printStackTrace()
        }

        Log.d(TAG, "toBytes contentStr:$contentStr")
        return bos.toByteArray()
    }



 fun build(reader: BufferedSource): DefaultPacket {
            val packet = DefaultPacket()
            /* packet.length = reader.readInt()
             packet.cmd = reader.readInt()
             packet.seq = reader.readInt()
             //减去协议头的12个字节长度
             packet.contentStr = reader.readString((packet.length - 12).toLong(), Charset.defaultCharset())*/

            packet.contentStr = reader.readString(Charset.defaultCharset())

            try {
                val resp = Gson().fromJson(packet.contentStr, ResponseBean::class.java)
                packet.cmd = resp.cmd ?: 0
                packet.requestId = resp.requestId.toString()

            } catch (e: Exception) {

            }

            Log.d("DefaultPacket", "build $packet")
            return packet
        }

我发送的json 如下：

{"cmd":0,"inputs":[{"intent":"SCANWLAN"}],"packetId":"0","requestId":"8876f0fa-528d-4a89-9f64-5004f9ffe50e"}

**Comment by kolyneh** [comment]
发送时的Log:

D/DefaultPacketFactory: getRequestPacket reusable:null command:0 body:[size=108 text={"cmd":0,"inputs":[{"intent":"SCANWLAN"}],"packetId":"0","reques…]
D/BuildTcpApi: postRequestHandle 发出请求： RequestContext{request=Request{command=0, body=[size=108 text={"cmd":0,"inputs":[{"intent":"SCANWLAN"}],"packetId":"0","reques…], description='扫描Wlan网络'}, responseHandler=bizsocket.rx2.BizSocketCall$1$1@292a2f0b}
D/DefaultPacket: toBytes contentStr:{"cmd":0,"inputs":[{"intent":"SCANWLAN"}],"packetId":"0","requestId":"8876f0fa-528d-4a89-9f64-5004f9ffe50e"}
I/System.out: cmd: 0Packet: -------------------send packet: 0 ,desc: 扫描Wlan网络, id: eb028735-acae-4b2d-a92c-3ecb5d018600
I/System.out: Packet: -------------------send content: {"cmd":0,"inputs":[{"intent":"SCANWLAN"}],"packetId":"0","requestId":"8876f0fa-528d-4a89-9f64-5004f9ffe50e"}

**Comment by typ0520** [comment]
先查发给服务器的数据是否正确，然后再查解析；我不知道你们的协议，给我看这些我也看不出问题的

**Comment by kolyneh** [comment]
嗯嗯，服务器已经收到了，用工具查看服务器的数据确实下发了， 但是client就是接受不到。
client有没有在解析前打印数据的地方？
